layout_spectrum: 0
color:
  saturation: 0.2133205
  lightness: 0.8775657
  brandStrength: 0.4119849
  rhythmicContrast: 0.3154798
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.8601316
name: 'Cat & Fish'
